const http = require('http');
const crypto = require('crypto');
const fs = require('fs');
const path = require('path');
const { Pool } = require('pg');

const PORT = Number(process.env.PORT || 8080);
const HOST = process.env.HOST || '0.0.0.0';
const WEB_ORIGIN = process.env.WEB_ORIGIN || '*';
const DATABASE_URL = process.env.DATABASE_URL;
const SESSION_PEPPER = process.env.SESSION_PEPPER || 'nexo-change-this';
const pool = new Pool({ connectionString: DATABASE_URL, ssl: process.env.PGSSL === 'true' ? { rejectUnauthorized: false } : undefined });
const pending = new Map();
const twoFactorChallenges = new Map();
const clients = new Map();
const online = new Set();

const token = () => crypto.randomBytes(32).toString('hex');
const id = (prefix = 'id') => `${prefix}_${crypto.randomBytes(10).toString('hex')}`;
const hash = (value) => crypto.createHash('sha256').update(String(value)).digest('hex');
const sessionHash = (value) => hash(`${SESSION_PEPPER}:${value}`);
const usernameOf = (value) => String(value || '').trim().toLowerCase();
const nowIso = () => new Date().toISOString();

function base32Encode(buffer) {
  const alphabet = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ234567'; let bits = 0; let value = 0; let output = '';
  for (const byte of buffer) { value = (value << 8) | byte; bits += 8; while (bits >= 5) { output += alphabet[(value >>> (bits - 5)) & 31]; bits -= 5; } }
  if (bits) output += alphabet[(value << (5 - bits)) & 31]; return output;
}
function base32Decode(input) {
  const alphabet = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ234567'; let bits = 0; let value = 0; const bytes = [];
  for (const char of String(input || '').replace(/=+$/, '').toUpperCase()) { const n = alphabet.indexOf(char); if (n < 0) continue; value = (value << 5) | n; bits += 5; if (bits >= 8) { bytes.push((value >>> (bits - 8)) & 255); bits -= 8; } }
  return Buffer.from(bytes);
}
function totp(secret, offset = 0) { const key = base32Decode(secret); const counter = Math.floor(Date.now() / 30000) + offset; const buffer = Buffer.alloc(8); buffer.writeBigUInt64BE(BigInt(counter)); const digest = crypto.createHmac('sha1', key).update(buffer).digest(); const start = digest[digest.length - 1] & 15; const number = ((digest[start] & 127) << 24) | (digest[start + 1] << 16) | (digest[start + 2] << 8) | digest[start + 3]; return String(number % 1000000).padStart(6, '0'); }
function validTotp(secret, code) { const value = String(code || '').replace(/\s/g, ''); return [-1, 0, 1].some((offset) => totp(secret, offset) === value); }
function otpUri(username, secret) { return `otpauth://totp/Nexo:${encodeURIComponent(username)}?secret=${secret}&issuer=Nexo&algorithm=SHA1&digits=6&period=30`; }
function generateSecret() { return base32Encode(crypto.randomBytes(20)); }
function backupCodes() { return Array.from({ length: 8 }, () => crypto.randomBytes(4).toString('hex').toUpperCase()); }
function passwordHash(password) { return hash(`${SESSION_PEPPER}:password:${password}`); }

function cors(req) { const origin = req.headers.origin; return { ...(WEB_ORIGIN === '*' ? { 'Access-Control-Allow-Origin': '*' } : (origin === WEB_ORIGIN ? { 'Access-Control-Allow-Origin': origin, Vary: 'Origin' } : {})), 'Access-Control-Allow-Headers': 'Content-Type, Authorization', 'Access-Control-Allow-Methods': 'GET, POST, PUT, OPTIONS' }; }
function send(res, status, payload, extra = {}) { const body = JSON.stringify(payload); res.writeHead(status, { ...cors(res.req || { headers: {} }), 'Content-Type': 'application/json; charset=utf-8', 'Cache-Control': 'no-store', 'Content-Length': Buffer.byteLength(body), ...extra }); res.end(body); }
function fail(res, status, message, code = 'error') { return send(res, status, { error: message, code }); }
function readBody(req, limit = 10 * 1024 * 1024) { return new Promise((resolve, reject) => { let body = ''; let size = 0; req.setEncoding('utf8'); req.on('data', (chunk) => { size += Buffer.byteLength(chunk); if (size > limit) { reject(Object.assign(new Error('Слишком большой запрос'), { statusCode: 413 })); req.destroy(); return; } body += chunk; }); req.on('end', () => { if (!body) return resolve({}); try { resolve(JSON.parse(body)); } catch { reject(Object.assign(new Error('Некорректный JSON'), { statusCode: 400 })); } }); req.on('error', reject); }); }
function bearer(req) { const value = String(req.headers.authorization || ''); return value.startsWith('Bearer ') ? value.slice(7) : ''; }
async function currentUser(req) { const raw = bearer(req); if (!raw) return null; const result = await pool.query(`SELECT u.id,u.username,u.display_name,u.email,u.two_factor FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=$1 AND s.expires_at>now()`, [sessionHash(raw)]); return result.rows[0] || null; }
function publicUser(row) { return { username: row.username, name: row.display_name, email: row.email, online: online.has(row.username), profile: row.profile || {}, avatarImage: row.profile?.avatarImage || null, premium: !!row.profile?.premium, premiumNumber: row.profile?.showNumber ? (row.profile?.premiumNumber || '') : '' }; }
async function userByUsername(username) { const result = await pool.query(`SELECT u.id,u.username,u.display_name,u.email,u.two_factor,COALESCE(p.data,'{}'::jsonb) AS profile FROM users u LEFT JOIN profiles p ON p.user_id=u.id WHERE u.username=$1`, [username]); return result.rows[0] || null; }
function issueSession(username) { const raw = token(); return pool.query(`INSERT INTO sessions(token_hash,user_id,expires_at) SELECT $1,id,now()+interval '30 days' FROM users WHERE username=$2`, [sessionHash(raw), username]).then(() => raw); }
function broadcast(username, event, payload) { const set = clients.get(username); if (!set) return; const packet = `event: ${event}\ndata: ${JSON.stringify(payload)}\n\n`; for (const res of [...set]) { try { res.write(packet); } catch { set.delete(res); } } }
function setOnline(username, value) { if (value) online.add(username); else online.delete(username); }
function openEvents(req, res, user) { res.writeHead(200, { ...cors(req), 'Content-Type': 'text/event-stream; charset=utf-8', 'Cache-Control': 'no-cache, no-transform', Connection: 'keep-alive', 'X-Accel-Buffering': 'no' }); res.write(': ' + ' '.repeat(2048) + '\n\n'); res.write(`event: ready\ndata: ${JSON.stringify({ username: user.username })}\n\n`); if (!clients.has(user.username)) clients.set(user.username, new Set()); clients.get(user.username).add(res); setOnline(user.username, true); const close = () => { clients.get(user.username)?.delete(res); if (!clients.get(user.username)?.size) { clients.delete(user.username); setOnline(user.username, false); } }; req.on('close', close); req.on('error', close); }
setInterval(() => { for (const set of clients.values()) for (const res of set) { try { res.write(': keep-alive\n\n'); } catch {} } }, 25000).unref();
async function stateFor(userId) { const result = await pool.query(`SELECT groups_data,chat_meta,settings FROM user_state WHERE user_id=$1`, [userId]); return result.rows[0] || { groups_data: [], chat_meta: {}, settings: {} }; }
async function saveState(userId, body) { await pool.query(`INSERT INTO user_state(user_id,groups_data,chat_meta,settings,updated_at) VALUES($1,$2,$3,$4,now()) ON CONFLICT(user_id) DO UPDATE SET groups_data=COALESCE($2,user_state.groups_data),chat_meta=COALESCE($3,user_state.chat_meta),settings=COALESCE($4,user_state.settings),updated_at=now()`, [userId, body.groups || null, body.chatMeta || null, body.settings || null]); if (body.profile) await pool.query(`INSERT INTO profiles(user_id,data,updated_at) VALUES($1,$2,now()) ON CONFLICT(user_id) DO UPDATE SET data=profiles.data || $2,updated_at=now()`, [userId, body.profile]); }
function directNames(chatId) { const match = /^dm:([^:]+):([^:]+)$/.exec(chatId); return match ? [usernameOf(match[1]), usernameOf(match[2])] : []; }
async function ensureDirect(chatId, user) { const names = directNames(chatId); if (names.length !== 2 || !names.includes(user.username)) return null; const rows = await pool.query(`SELECT id,username FROM users WHERE username=ANY($1::text[])`, [names]); if (rows.rows.length !== 2) return null; await pool.query(`INSERT INTO conversations(id,kind) VALUES($1,'direct') ON CONFLICT(id) DO NOTHING`, [chatId]); for (const row of rows.rows) await pool.query(`INSERT INTO conversation_members(conversation_id,user_id) VALUES($1,$2) ON CONFLICT DO NOTHING`, [chatId, row.id]); return rows.rows; }
async function memberUsernames(chatId) { const result = await pool.query(`SELECT u.id,u.username FROM conversation_members cm JOIN users u ON u.id=cm.user_id WHERE cm.conversation_id=$1`, [chatId]); return result.rows; }
async function profileFor(userId) { const result = await pool.query(`SELECT data FROM profiles WHERE user_id=$1`, [userId]); return result.rows[0]?.data || {}; }
async function reactionsFor(messageId, userId) { const result = await pool.query(`SELECT emoji,user_id FROM reactions WHERE message_id=$1`, [messageId]); const counts = {}; const mine = []; for (const row of result.rows) { counts[row.emoji] = (counts[row.emoji] || 0) + 1; if (Number(row.user_id) === Number(userId)) mine.push(row.emoji); } return { reactions: counts, myReactions: mine }; }
async function messageDto(row, userId) { const reaction = await reactionsFor(row.id, userId); let status = ''; if (Number(row.sender_id) === Number(userId)) status = row.read_at ? 'read' : row.delivered_at ? 'delivered' : 'sent'; return { id: row.id, from: Number(row.sender_id) === Number(userId) ? 'me' : 'them', text: row.deleted ? '' : row.content, type: row.message_type, rich: !!row.rich, edited: !!row.edited, deleted: !!row.deleted, time: new Date(row.created_at).toISOString().slice(11, 16), status, ...reaction }; }
async function messagesFor(chatId, userId, limit = 100) { const result = await pool.query(`SELECT * FROM messages WHERE conversation_id=$1 ORDER BY created_at DESC,id DESC LIMIT $2`, [chatId, Math.min(Math.max(limit, 1), 200)]); const rows = []; for (const row of result.rows.reverse()) rows.push(await messageDto(row, userId)); return rows; }
async function canShowRead(userId) { const profile = await profileFor(userId); return profile.premium ? profile.showReadReceipts !== false : true; }
function aiReply(text) { const value = String(text || '').trim(); const lower = value.toLowerCase(); if (!value) return 'Напиши вопрос — я помогу.'; if (lower.includes('что ты умеешь') || lower === 'help') return '🤖 Я помогу составить план, чек-лист, код, сообщение, таблицу и объяснение. Для настоящей нейросети подключим AI API отдельно.'; if (/^[\d\s+\-*/().,^]+$/.test(value) && /[+\-*/]/.test(value)) { try { const result = Function(`return (${value.replace(/\^/g, '**')})`)(); if (Number.isFinite(result)) return '🧮 Результат: ' + result; } catch {} } if (lower.includes('привет')) return 'Привет! Серверный AI на связи.'; return 'Запрос получен. Уточни, нужен план, код, сообщение или объяснение.'; }

async function api(req, res, url) {
  res.req = req;
  if (req.method === 'OPTIONS') { res.writeHead(204, cors(req)); return res.end(); }
  if (req.method === 'GET' && url.pathname === '/api/health') return send(res, 200, { ok: true, service: 'nexo-postgres-backend', mode: 'postgres-mvp' });
  if (req.method === 'POST' && url.pathname === '/api/auth/register/start') { const b = await readBody(req, 128000); const username = usernameOf(b.username); const email = String(b.email || '').trim().toLowerCase(); const name = String(b.name || '').trim().slice(0, 80); const password = String(b.password || ''); if (!name || !email || !username || password.length < 6) return fail(res, 400, 'Заполни поля и используй пароль от 6 символов.'); const duplicate = await pool.query('SELECT 1 FROM users WHERE username=$1 OR email=$2', [username, email]); if (duplicate.rowCount) return fail(res, 409, 'Логин или email уже заняты.'); const code = String(crypto.randomInt(100000, 1000000)); pending.set(username, { name, email, password, code, expires: Date.now() + 600000 }); console.log('Код регистрации для', username, code); return send(res, 200, { ok: true, devCode: process.env.DEV_MODE === 'false' ? undefined : code }); }
  if (req.method === 'POST' && url.pathname === '/api/auth/register/confirm') { const b = await readBody(req, 64000); const username = usernameOf(b.username); const item = pending.get(username); if (!item || item.expires < Date.now() || String(b.code) !== item.code) return fail(res, 400, 'Неверный или просроченный код.'); const result = await pool.query(`INSERT INTO users(username,display_name,email,password_hash) VALUES($1,$2,$3,$4) RETURNING id`, [username, item.name, item.email, passwordHash(item.password)]); await pool.query(`INSERT INTO profiles(user_id,data) VALUES($1,'{}'::jsonb) ON CONFLICT DO NOTHING`, [result.rows[0].id]); await pool.query(`INSERT INTO user_state(user_id) VALUES($1) ON CONFLICT DO NOTHING`, [result.rows[0].id]); pending.delete(username); return send(res, 201, { ok: true }); }
  if (req.method === 'POST' && url.pathname === '/api/auth/login') { const b = await readBody(req, 64000); const row = await userByUsername(usernameOf(b.username)); if (!row || row.password_hash && row.password_hash !== passwordHash(b.password)) return fail(res, 401, 'Неверный логин или пароль.'); if (row.two_factor?.enabled) { const challenge = token(); twoFactorChallenges.set(challenge, { username: row.username, expires: Date.now() + 180000 }); return send(res, 200, { requires2FA: true, challengeToken: challenge, user: publicUser(row) }); } const t = await issueSession(row.username); return send(res, 200, { token: t, user: publicUser(row) }); }
  if (req.method === 'POST' && url.pathname === '/api/auth/login/2fa') { const b = await readBody(req); const challenge = twoFactorChallenges.get(String(b.challengeToken || '')); if (!challenge || challenge.expires < Date.now()) return fail(res, 401, 'Сессия 2FA истекла.'); const row = await userByUsername(challenge.username); let accepted = validTotp(row.two_factor.secret, b.code); if (!accepted && Array.isArray(row.two_factor.backupCodes)) { const index = row.two_factor.backupCodes.indexOf(String(b.code || '').trim().toUpperCase()); if (index >= 0) { row.two_factor.backupCodes.splice(index, 1); await pool.query('UPDATE users SET two_factor=$1 WHERE id=$2', [row.two_factor, row.id]); accepted = true; } } if (!accepted) return fail(res, 401, 'Неверный код 2FA.'); twoFactorChallenges.delete(String(b.challengeToken)); const t = await issueSession(row.username); return send(res, 200, { token: t, user: publicUser(row) }); }
  const user = await currentUser(req); if (!user) return fail(res, 401, 'Нужна авторизация.');
  if (req.method === 'POST' && url.pathname === '/api/auth/logout') { await pool.query('DELETE FROM sessions WHERE token_hash=$1', [sessionHash(bearer(req))]); setOnline(user.username, false); return send(res, 200, { ok: true }); }
  if (req.method === 'GET' && url.pathname === '/api/events') return openEvents(req, res, user);
  if (req.method === 'GET' && url.pathname === '/api/contacts') { const q = String(url.searchParams.get('q') || '').toLowerCase(); const result = await pool.query(`SELECT u.id,u.username,u.display_name,u.email,COALESCE(p.data,'{}'::jsonb) AS profile FROM users u LEFT JOIN profiles p ON p.user_id=u.id WHERE u.id<>$1 AND ($2='' OR u.username ILIKE '%'||$2||'%' OR u.display_name ILIKE '%'||$2||'%') ORDER BY u.display_name LIMIT 100`, [user.id, q]); return send(res, 200, { contacts: result.rows.map(publicUser) }); }
  if (req.method === 'GET' && url.pathname === '/api/state') { const state = await stateFor(user.id); const conversations = await pool.query(`SELECT cm.conversation_id FROM conversation_members cm WHERE cm.user_id=$1`, [user.id]); const chats = {}; for (const row of conversations.rows) chats[row.conversation_id] = await messagesFor(row.conversation_id, user.id); return send(res, 200, { state: { chats, groups: state.groups_data || [], chatMeta: state.chat_meta || {}, profile: await profileFor(user.id), settings: state.settings || {} } }); }
  if (req.method === 'POST' && url.pathname === '/api/state') { const b = await readBody(req, 12 * 1024 * 1024); await saveState(user.id, b); return send(res, 200, { ok: true }); }
  if (req.method === 'GET' && url.pathname === '/api/auth/2fa/status') return send(res, 200, { enabled: !!user.two_factor?.enabled });
  if (req.method === 'POST' && url.pathname === '/api/auth/2fa/setup') { if (user.two_factor?.enabled) return send(res, 200, { enabled: true }); const secret = generateSecret(); await pool.query('UPDATE users SET two_factor=$1 WHERE id=$2', [{ enabled: false, pendingSecret: secret, backupCodes: [] }, user.id]); return send(res, 200, { enabled: false, secret, otpauth: otpUri(user.username, secret) }); }
  if (req.method === 'POST' && url.pathname === '/api/auth/2fa/enable') { const b = await readBody(req); const secret = user.two_factor?.pendingSecret; if (!secret || !validTotp(secret, b.code)) return fail(res, 400, 'Неверный код из приложения.'); const codes = backupCodes(); await pool.query('UPDATE users SET two_factor=$1 WHERE id=$2', [{ enabled: true, secret, backupCodes: codes }, user.id]); return send(res, 200, { enabled: true, backupCodes: codes }); }
  if (req.method === 'POST' && url.pathname === '/api/auth/2fa/disable') { const b = await readBody(req); if (!user.two_factor?.enabled || !validTotp(user.two_factor.secret, b.code)) return fail(res, 400, 'Неверный код.'); await pool.query('UPDATE users SET two_factor=$1 WHERE id=$2', [{ enabled: false, backupCodes: [] }, user.id]); return send(res, 200, { enabled: false }); }
  if (req.method === 'POST' && url.pathname === '/api/ai/reply') { const b = await readBody(req); return send(res, 200, { reply: aiReply(b.text) }); }

  const messageMatch = /^\/api\/chats\/([^/]+)\/messages$/.exec(url.pathname);
  if (messageMatch) { const chatId = decodeURIComponent(messageMatch[1]); const members = await ensureDirect(chatId, user); if (!members) return fail(res, 403, 'Нет доступа к этому чату.'); if (req.method === 'GET') return send(res, 200, { messages: await messagesFor(chatId, user.id) }); if (req.method === 'POST') { const b = await readBody(req, 10 * 1024 * 1024); if (!b.text) return fail(res, 400, 'Пустое сообщение.'); const messageId = b.clientMessageId || id('msg'); const recipient = members.find((item) => item.username !== user.username); const recipientOnline = online.has(recipient.username); const result = await pool.query(`INSERT INTO messages(id,conversation_id,sender_id,content,message_type,rich,delivered_at) VALUES($1,$2,$3,$4,$5,$6,$7) ON CONFLICT(id) DO NOTHING RETURNING *`, [messageId, chatId, user.id, String(b.text), b.type || 'text', !!b.rich, recipientOnline ? new Date() : null]); if (!result.rowCount) return send(res, 200, { ok: true, messageId }); const senderMessage = await messageDto(result.rows[0], user.id); const recipientMessage = await messageDto(result.rows[0], recipient.id); recipientMessage.from = 'them'; broadcast(recipient.username, 'message', { chatId, message: recipientMessage }); if (recipientOnline) broadcast(user.username, 'message_status', { chatId, messageId, status: 'delivered' }); return send(res, 201, { ok: true, message: senderMessage }); } }
  const editMatch = /^\/api\/chats\/([^/]+)\/messages\/([^/]+)\/edit$/.exec(url.pathname); if (editMatch && req.method === 'POST') { const chatId = decodeURIComponent(editMatch[1]); const messageId = decodeURIComponent(editMatch[2]); const b = await readBody(req); const text = String(b.text || '').trim(); const members = await ensureDirect(chatId, user); if (!members || !text) return fail(res, 400, 'Не удалось изменить сообщение.'); await pool.query(`UPDATE messages SET content=$1,edited=true WHERE id=$2 AND sender_id=$3`, [text, messageId, user.id]); const recipient = members.find((item) => item.username !== user.username); broadcast(recipient.username, 'message_updated', { chatId, messageId, text, edited: true }); return send(res, 200, { ok: true }); }
  const deleteMatch = /^\/api\/chats\/([^/]+)\/messages\/([^/]+)\/delete$/.exec(url.pathname); if (deleteMatch && req.method === 'POST') { const chatId = decodeURIComponent(deleteMatch[1]); const messageId = decodeURIComponent(deleteMatch[2]); const members = await ensureDirect(chatId, user); if (!members) return fail(res, 400, 'Не удалось удалить сообщение.'); await pool.query(`UPDATE messages SET deleted=true,content='' WHERE id=$1 AND sender_id=$2`, [messageId, user.id]); const recipient = members.find((item) => item.username !== user.username); broadcast(recipient.username, 'message_deleted', { chatId, messageId }); return send(res, 200, { ok: true }); }
  const reactionMatch = /^\/api\/chats\/([^/]+)\/messages\/([^/]+)\/reaction$/.exec(url.pathname); if (reactionMatch && req.method === 'POST') { const chatId = decodeURIComponent(reactionMatch[1]); const messageId = decodeURIComponent(reactionMatch[2]); const b = await readBody(req); const members = await ensureDirect(chatId, user); const emoji = String(b.emoji || '').slice(0, 16); if (!members || !emoji) return fail(res, 400, 'Не удалось сохранить реакцию.'); if (b.active === false) await pool.query('DELETE FROM reactions WHERE message_id=$1 AND user_id=$2 AND emoji=$3', [messageId, user.id, emoji]); else await pool.query('INSERT INTO reactions(message_id,user_id,emoji) VALUES($1,$2,$3) ON CONFLICT DO NOTHING', [messageId, user.id, emoji]); const recipient = members.find((item) => item.username !== user.username); const reactions = await reactionsFor(messageId, recipient.id); broadcast(recipient.username, 'reaction_updated', { chatId, messageId, ...reactions }); return send(res, 200, { ok: true }); }
  const readMatch = /^\/api\/chats\/([^/]+)\/read$/.exec(url.pathname); if (readMatch && req.method === 'POST') { const chatId = decodeURIComponent(readMatch[1]); const b = await readBody(req); if (!(await canShowRead(user.id))) return send(res, 200, { ok: true, disabled: true }); const ids = Array.isArray(b.messageIds) ? b.messageIds.slice(0, 100) : []; for (const messageId of ids) { const row = await pool.query(`UPDATE messages SET read_at=now() WHERE id=$1 AND conversation_id=$2 AND sender_id<>$3 RETURNING sender_id`, [messageId, chatId, user.id]); if (row.rowCount) { const sender = await pool.query('SELECT username FROM users WHERE id=$1', [row.rows[0].sender_id]); if (sender.rowCount) broadcast(sender.rows[0].username, 'message_status', { chatId, messageId, status: 'read' }); } } return send(res, 200, { ok: true }); }
  if (req.method === 'POST' && url.pathname === '/api/calls/signal') { const b = await readBody(req); const to = usernameOf(b.to); const target = await userByUsername(to); if (!target) return fail(res, 404, 'Пользователь не найден.'); broadcast(to, 'call', { from: user.username, fromName: user.display_name, callId: b.callId, kind: b.kind, data: b.data, mediaType: b.mediaType === 'video' ? 'video' : 'audio' }); return send(res, 200, { ok: true }); }
  return fail(res, 404, 'Route not found.');
}

const server = http.createServer(async (req, res) => { try { const url = new URL(req.url, `http://${req.headers.host || 'localhost'}`); if (!url.pathname.startsWith('/api/')) return send(res, 404, { message: 'Nexo Postgres backend' }); await api(req, res, url); } catch (error) { console.error('[nexo-postgres]', error); if (!res.headersSent) fail(res, error.statusCode || 500, error.message || 'Server error'); else res.end(); } });
async function init() { if (!DATABASE_URL) throw new Error('DATABASE_URL is missing'); const schema = fs.readFileSync(path.join(__dirname, 'schema.sql'), 'utf8'); await pool.query(schema); server.listen(PORT, HOST, () => console.log(`Nexo PostgreSQL backend: http://${HOST}:${PORT}`)); }
init().catch((error) => { console.error(error.message); process.exit(1); });
